# Assignment 1
Done by:
- Saumili Jana: 20ME10075
- Ushasi Das: 20EC10086
- Jaya Kishnani: 20EC30020
- Karthikeyan.R: 20EC30024

In [1]:
#importing modules
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

We import the data as panda's dataframes, split them into training and test dataset, and convert them into numpy array. As mentioned in the problem statement, the last 15 samples in the dataset have been put in the test set.

In [2]:
#importing the dataset
all_data = pd.read_csv('sobar-72.csv')
print(all_data)

    behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                    10               13                       12   
1                    10               11                       11   
2                    10               15                        3   
3                    10               11                       10   
4                     8               11                        7   
..                  ...              ...                      ...   
67                   10               14                       14   
68                   10               12                       15   
69                   10                8                       11   
70                    9               12                       13   
71                   10               14                       14   

    intention_aggregation  intention_commitment  attitude_consistency  \
0                       4                     7                     9   
1                      10

In [3]:
#splitting the dataset into training and test datasets
train_data = all_data.head(57) #training set
test_data = all_data.tail(15)  #test set
#print(train_data)
#print(test_data)

In [4]:
#converting to numpy arrays for ease of computation
all_arr = all_data.to_numpy()
train_arr = train_data.to_numpy()  #training set converted to numpy array
#print(train_arr)
test_arr = test_data.to_numpy() #test set converted to numpy array
print(test_arr)

[[10 11  8 10 15  7  8  5 14 13  8 12  7  4  3  3  4  4  7  0]
 [10 11  9  6 15  6  8  5 14 11  8 11  7  3  2  3  3  3  3  0]
 [10 13  9 10 15  8  8  5 14  8  8 11  3  3  2  3  3  3  3  0]
 [10 12 10 10 15  6  8  5 15 11  8 13  7  3  2  3  3  3  3  0]
 [10 10 10 10 15  6  6  5 14 13  9 15  9 13  8 14 13 12 12  0]
 [10 13 11  6 15  8 10  5 15  7 10 13  7  3  5  3  3  3  3  0]
 [10 13 15 10 15  8 10  5 14  6  8 13  7  3  4  3  3  6  3  0]
 [10 15  8  6 11  6 10  5 11 15  8 15  7  3  4 11 13 10 15  0]
 [10 13 11  6 14  9 10  5 15 15 10 15  3  3  4  7  7  7 11  0]
 [10 12 13 10 11  7  7  5 14 15  9 14 10  6  6  6  9  7 11  0]
 [10 14 14 10 15  6  7  5 15 14 10 15 13  9  8 12 12 11  9  0]
 [10 12 15 10 15  8  8  5 15 14  8 12 14 11  7 13 15 11 14  0]
 [10  8 11  6 10  6  4  3 13  9  8 14 12  9  7 11 12 10 10  0]
 [ 9 12 13 10 13  6  6  5 14 13 10 13 12 11  8 12 11 13 15  0]
 [10 14 14  6 12  7  8  5 15 12 10 10 13 11  9 14 13 15 15  0]]


We use the minkowski distance with power(and root) as 4 for calculating the distances between the samples

In [5]:
#Function for calculating distances

#minkowski distance
def minkowski(point1, point2):
    p = 4
    point1 = point1[:-1]
    point2 = point2[:-1]
    a = np.subtract(point1,point2) 
    a = np.absolute(a)
    a = np.power(a, p)
    s = np.sum(a)
    dist = s**(1/p)
    return(dist)
    
#check = minkowski([2,3,4],[1,1,1])//For checking the working of the function
#check



## Condensed KNN

We first define a function which figure out the nearest neighbour for a sample. And then we use this function to condense the dataset as per the condensed nearest neighbour algorithm.

In [6]:
#Function for finding out the nearest neighbour(1-NN), will be used for condensing

def nrst_nbr(frame,point):
    min = None
    for row in frame:
        d = minkowski(row,point)
        if min is None:
            min = d
            x = row
        elif d<min:
            min = d
            x = row
    return(x)
        
#test the function
#a = np.array([[1,1,1],[0.5,0.5,0.5], [0.1,0.1,0.1],[2,2,2]])
#p = np.array([0,0,0])
#z = nrst_nbr(a,p)
#z

#Test successful!!
    

In [7]:
(r,c)=train_arr.shape
c

20

In [8]:
#Condensing the training dataset# condensed knn algorithm

train_arr1 = train_arr #making a copy, so that original dataset doesn't change during operation

S = np.array(train_arr[0] ,ndmin=2) # initialised set S with he first element
index = 0
flag = 0
while True:
    for row in train_arr1:
        #print(row)
        a = nrst_nbr(S,row) #a contains the the row in S which is closest to the point in the training data being tested
        if a[19]!=row[19]:  #misclassified
            flag = 1
            S = np.vstack((S,row)) #Add to set S if misclassified
            np.delete(train_arr1,index,axis=0) #delete that point from the dataset
            break
        (r,c) = train_arr1.shape
        index = index+1
        if (index==r):
            break
    if (flag==0): #Stops the iteration, when S does not change
        break
    flag = 0
    index = 0   
print('final condensed set', S)
#print(S.shape)    

final condensed set [[10 13 12  4  7  9 10  1  8  7  3 14  8  5  7 12 12 11  8  1]
 [10 12 11 10 15  7  8  3  3  3  2 13 11 10  7 12 12 12 12  0]
 [10 11 10 10 15  7  7  1  5  4  2 15 13  7  4  4  4  4  4  1]
 [10 14  8  6 15  8 10  1  3  4  2 14  8  7  2  7 13  9  6  1]
 [ 8 12  9 10 10  5 10  5  5  5  2 10  9 13  2  9  8  7 12  1]
 [10 15  7  2 15  6 10  1  3  5  2  9 15 13 10 15 13 15 15  1]
 [10 15 12 10 15  6 10  1  3  3  2  4  3  3  2 15 13  6 11  1]
 [ 9 12 14  9 15 10  9  3  6  3  2 15 15  3 10 15 11  3 11  1]
 [10  3  5  2  9  6 10  1  3  9  6 11 10  9  9 14  6 10 10  0]
 [10 15  9  3 15  8 10  1  3  5  6 10 15 13 10 15 15 15 15  0]
 [10 10 12  5  7  6  6  4  5 10  4 11  9 11  8 11 11 10 11  0]
 [10 15  7  6 14  8  8  4  8 10  2  3  3  3  2  5  5  5  3  1]
 [10 12 12  8 10  8  6  2  7  6  2 12 11  9  8 12 10 10  9  1]
 [10 13 15  8 13  7  8  3  5  9  2 13 11 12  9 10 12 13 12  0]
 [10 14 10  9 15  4  5  2  5  7  3 10  7  4  6  7  5  9 12  0]
 [10 15  3  2 14  8 10  1  4  7  2 

We have obtained the condensed set S. Now we will use this condensed set S for classifying the test samples according to the K-NN classification for k = 5 

In [9]:
#clasifier function-will be used for the final condensed K-NN(k=5) classification
def classify(five_nn): #input is the output labels of 5 neighbours
    track = 0
    for k in five_nn: #tracks the numbe of zeroes and 1s
        if (k == 1):
            track += 1
    if (track>2.5):
        return 1
    else:
        return 0 #returns the output of test sample

In [10]:
#5-NN classification on the condensed data set

y_pred = [] #array of final predicted labels

for i in test_arr:
    store = np.empty((0,20), float)
    distances = []
    for j in S:
        dis = minkowski(i,j) #calculates the distance
        distances.append(dis)
    dist_arr = np.array(distances)
    dist_arr_1 = np.array(distances)
    dist_arr.sort()
    #print(dist_arr)
    #print(dist_arr_1)
    #(index,) = np.where(dist_arr_1 == dist_arr[count])
    #print(index[0])
    count = 0
    while (count<5):
        
        (index,) = np.where(dist_arr_1 == dist_arr[count])
        store = np.vstack((store,S[index[0]])) #stores the features and labels of 5 nearest neighbours
        count = count + 1
    #print(store[:,19])
    label = classify(store[:,19]) #predicted output label of the test sample
    #print(label)
    y_pred.append(label)
    
print(y_pred)
      

[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]


#### Calculating the accuracy of our prediction for the condensed KNN

In [11]:
#Accuracy function
def accuracy(pred , y_test):
    count = 0
    for i in range(len(pred)):
        if pred[i] == y_test[i]:
            count +=1
            
    return (count/len(pred))*100

In [12]:
y_test = test_arr[:,19]
acc_cnn = accuracy(y_pred,y_test)
print("Accuracy = ",acc_cnn, " %")

Accuracy =  86.66666666666667  %


## Standard KNN

Now we perform a standard K-NN classification with k = 5, and compare our results

In [13]:
#Standard 5-NN classification
y_pred_knn = []#array of final predicted labels
store = np.empty((0,3), float)
x_test = test_arr[:,:19] 

for i in test_arr:
    store = np.empty((0,20), float)
    distances = []
    for j in train_arr:
        dis = minkowski(i,j) #calculates the distance
        distances.append(dis)
    dist_arr = np.array(distances)
    dist_arr_1 = np.array(distances)
    dist_arr.sort()
    #print(dist_arr)
    #print(dist_arr_1)
    #(index,) = np.where(dist_arr_1 == dist_arr[count])
    #print(index[0])
    count = 0
    while (count<5):
        
        (index,) = np.where(dist_arr_1 == dist_arr[count])
        store = np.vstack((store,train_arr[index[0]])) #stores the features and labels of 5 nearest neighbours
        count = count + 1
    print(store[:,19])
    label = classify(store[:,19])
    #print(label)
    y_pred_knn.append(label) #predicted output label of the test sample
    
print(y_pred_knn)

[1. 1. 0. 0. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[1. 1. 0. 1. 0.]
[1. 0. 1. 1. 1.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]


#### Calculating the accuracy of our prediction for the standard KNN

In [14]:
y_test = test_arr[:,19] 
acc_knn = accuracy(y_pred_knn,y_test)
print("Accuracy = ",acc_knn, " %")

Accuracy =  73.33333333333333  %


### Writing the final results in a file

In [15]:
file = open('results.txt','w')
file.write("\t\t\tFINAL RESULTS\n\t\t       MLFA Assignment-1\n--------------------------------------------------------------\n--------------------------------------------------------------\n")
str1 = "Accuracy of Condensed KNN with k = 5 is " + str(acc_cnn) + " % "
file.write(str1)
str2 = "\nAccuracy of a standard KNN with k = 5 is " + str(acc_knn) + " % "
file.write(str2)
file.write("\n--------------------------------------------------------------\n--------------------------------------------------------------\n")
file.close()